// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRSapp.Model;

namespace PRSapp.Model.Migrations
{
    [DbContext(typeof(PRSappContext))]
    [Migration("20181226025451_2classesNqRecordSetClass")]
    partial class _2classesNqRecordSetClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PRSapp.Model.PlayList", b =>
                {
                    b.Property<int>("PlayListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Repeats");

                    b.Property<bool>("ShuffleIsOn");

                    b.Property<int>("UserId");

                    b.Property<string>("Uses");

                    b.HasKey("PlayListId");

                    b.ToTable("PlayLists");
                });

            modelBuilder.Entity("PRSapp.Model.PlayListItem", b =>
                {
                    b.Property<int>("PlayListItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemTitleId");

                    b.Property<string>("ItemTitleName");

                    b.Property<int>("PlayListId");

                    b.Property<int>("PlayPositions");

                    b.Property<int>("Priority");

                    b.HasKey("PlayListItemId");

                    b.HasIndex("PlayListId");

                    b.ToTable("PlayListItems");
                });

            modelBuilder.Entity("PRSapp.Model.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DirPath");

                    b.Property<string>("TitleName");

                    b.Property<string>("TtsRaw");

                    b.Property<int>("UserId");

                    b.HasKey("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("PRSapp.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserLogin");

                    b.Property<string>("UserPwd");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRSapp.Model.PlayListItem", b =>
                {
                    b.HasOne("PRSapp.Model.PlayList")
                        .WithMany("PlayListItems")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PRSapp.Model.Title", b =>
                {
                    b.HasOne("PRSapp.Model.User", "User")
                        .WithMany("Titles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
